backend:
  name: git-gateway
  branch: master


media_folder: content/assets/thumbs
public_folder_relative: true
public_folder: ../assets/thumbs

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    path: "/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      # - {label: "ファイルパス→ 「/〜」という形で", name: "path", widget: "string"}
      - {label: "公開日", name: "created", widget: "date"}
      - {label: "更新日", name: "updated", widget: "date"}
      - {label: "説明", name: "excerpt", widget: "text"}
      - {label: "サムネイル", name: "featuredImage", widget: "image"}
      - {label: "記事", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list"}