backend:
  name: git-gateway
  branch: master


media_folder: content/assets/thumbs

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{fields.path}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "url", name: "path", widget: "string"}
      - {label: "公開日", name: "created", widget: "date"}
      - {label: "更新日", name: "updated", widget: "date"}
      - {label: "説明", name: "excerpt", widget: "text"}
      - {label: "サムネイル", name: "featuredImage", widget: "image"}
      - {label: "記事", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list"}
      # - {label: "タグ", name: "tags", widget: "relation", collection: "categories" , multiple: true}

  # - name: 'categories'
  #   label: 'カテゴリ'
  #   folder: 'categories'
  #   create: true
  #   fields:
  #     - { label: 'カテゴリ名', name: 'title', widget: 'string' }
  #     - { label: '説明文', name: 'body', widget: 'text' }